### ISSUE TITLE
Sign of loss

### ISSUE THREAD

**Issue by Polkach** [haebeom-lee/dropmax#2]
Hello! I think you ought to change sign before net['ent'] in the loss function in your code. We are minimizing -H, where H is entropy.

**Comment by haebeom-lee** [comment]
Thank you for your comment!
Actually in the code, p*log(p) + (1-p)*log(p) is the negative of entropy, so the code is minimizing -H as you said.
But I just changed the name of the term from "entropy" to "neg_entropy" to clear up the confusion.
(We also just found out that in the paper Eq.(13), there is missing negative signs in the entropy term expression. We will correct it as soon as possible..... )
